MyProject/Models/Bar.cs
using System.Collections.Generic;

namespace MyProject.Models {
  public class Bar {
    public Bar() {
      this.JoinEntities = new HashSet <FooBar> ();
    }

    public int BarId {get; set;}
    public string Description {get; set;}
    public virtual ApplicationUser User {get; set;}

    public virtual ICollection <FooBar> JoinEntities {
      get;
    }
  }
}

MyProject/Controllers/BarsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using MyProject.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace MyProject.Controllers {
  [Authorize]
  public class BarsController: Controller {
    private readonly MyProjectContext _db;
    private readonly UserManager <ApplicationUser> _userManager;

    public BarsController(UserManager <ApplicationUser> userManager, MyProjectContext db) {
      _userManager = userManager;
      _db = db;
    }

    public async Task <ActionResult> Index() {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userBars = _db.Bars.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userBars);
    }

    public ActionResult Create() {
      ViewBag.FooId = new SelectList(_db.Foos, "FooId", "Name");
      return View();
    }

    [HttpPost]
    public async Task <ActionResult> Create(Bar Bar, int FooId) {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      Bar.User = currentUser;
      _db.Bars.Add(Bar);
      _db.SaveChanges();
      if (FooId != 0) {
        _db.FooBar.Add(new FooBar() {
          FooId = FooId, BarId = Bar.BarId
        });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id) {
      var thisBar = _db.Bars
        .Include(Bar => Bar.JoinEntities)
        .ThenInclude(join => join.Foo)
        .FirstOrDefault(Bar => Bar.BarId == id);
      return View(thisBar);
    }

    public ActionResult Edit(int id) {
      var thisBar = _db.Bars.FirstOrDefault(Bar => Bar.BarId == id);
      ViewBag.FooId = new SelectList(_db.Foos, "FooId", "Name");
      return View(thisBar);
    }

    [HttpPost]
    public ActionResult Edit(Bar Bar, int FooId) {
      if (FooId != 0) {
        _db.FooBar.Add(new FooBar() {
          FooId = FooId, BarId = Bar.BarId
        });
      }
      _db.Entry(Bar).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFoo(int id) {
      var thisBar = _db.Bars.FirstOrDefault(Bar => Bar.BarId == id);
      ViewBag.FooId = new SelectList(_db.Foos, "FooId", "Name");
      return View(thisBar);
    }

    [HttpPost]
    public ActionResult AddFoo(Bar Bar, int FooId) {
      if (FooId != 0) {
        _db.FooBar.Add(new FooBar() {
          FooId = FooId, BarId = Bar.BarId
        });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id) {
      var thisBar = _db.Bars.FirstOrDefault(Bar => Bar.BarId == id);
      return View(thisBar);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id) {
      var thisBar = _db.Bars.FirstOrDefault(Bar => Bar.BarId == id);
      _db.Bars.Remove(thisBar);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFoo(int joinId) {
      var joinEntry = _db.FooBar.FirstOrDefault(entry => entry.FooBarId == joinId);
      _db.FooBar.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

MyProject/Views/Bars/AddFoo.cshtml
@{
  Layout = "_Layout";
}

@model MyProject.Models.Bar

<h2>Add a Foo</h2>

<h4>Add a Foo to this Bar: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.BarId)

  <label for="FooId">Select Foo:</label>
  @Html.DropDownList("FooId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

MyProject/Views/Bars/Create.cshtml
@{
  Layout = "_Layout";
}

@model MyProject.Models.Bar

<h4>Add a new Bar</h4>

@using (Html.BeginForm())
{
  <label for="Description">Description:</label>
  @Html.TextBoxFor(model => model.Description)

  <label for="FooId">Select Foo:</label>
  @Html.DropDownList("FooId")

  <input type="submit" value="Add new Bar" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Bars", "Index")</p>

MyProject/Views/Bars/Delete.cshtml
@{
  Layout = "_Layout";
}

@model MyProject.Models.Bar

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

MyProject/Views/Bars/DeleteAll.cshtml
@* @{
  Layout = "_Layout";
}

<h1>Your list has been cleared!</h1>
<p><a href="/Bars">Back to list.</a></p> *@

MyProject/Views/Bars/Details.cshtml
@{
  Layout = "_Layout";
}

@model MyProject.Models.Bar

<h2>Bar Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Bar does not belong to any Foos</p>
}
else
{
  <h4>Foos the Bar belongs to:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Foo.Name</li>
    @using (Html.BeginForm("DeleteFoo", "Bars"))
    {
      @Html.Hidden("joinId", @join.FooBarId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Add a Foo", "AddFoo", new { id = Model.BarId })</p>

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Bar", "Edit", new { id = Model.BarId })</p>
<p>@Html.ActionLink("Delete Bar", "Delete", new { id = Model.BarId })</p>

MyProject/Views/Bars/Edit.cshtml
@{
  Layout = "_Layout";
}

@model MyProject.Models.Bar

<h2>Edit</h2>

<h4>Edit this Bar: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.BarId)

  <label for="Description">Description:</label>
  @Html.EditorFor(model => model.Description)

  <label for="FooId">Select Foo:</label>
  @Html.DropDownList("FooId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

MyProject/Views/Bars/Index.cshtml
@{
  Layout = "_Layout";
}

@using MyProject.Models;
@model IEnumerable<MyProject.Models.Bar>

<h1>Bars for @User.Identity.Name</h1>

@if (Model.Any())
{
  <ul>
    @foreach (Bar Bar in Model)
    {
      <li>@Html.ActionLink($"{Bar.Description}", "Details", new { id = Bar.BarId })</li>
    }
  </ul>
} 
else
{
  <h3>No Bars have been added yet!</h3>
}

<p>@Html.ActionLink("Add new Bar", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>